version: '2'

services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.1-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user1
      - MARIADB_DATABASE=my_database1
      - MARIADB_PASSWORD=my_password1

  myapp:
    tty: true
    image: 'docker.io/bitnami/codeigniter:3-debian-10'
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=my_user1
      - DB_DATABASE=my_database1
      - DB_PASSWORD=my_password1
    depends_on:
      - mariadb
    ports:
      - 80:3000
    volumes:
      - ./:/app
    # privileged: true # Privileged mode could be required to run this container under Windows
